# This is a basic workflow to help you get started with Actions

name: MyPipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Run one-line script
        run: |
          echo "build running"
          sleep 30
      - name: Run third file
        run: |
          echo "build completed"
          sleep 30
  job2:
    runs-on: self-hosted
    steps:
      - name: Run one-line script
        run: |
          echo "Test running"
          sleep 30
      - name: Run third file
        run: |
          echo "Test completed"
