# This is a basic workflow to help you get started with Actions

name: MyPipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run one-line script
        run: |
          echo "build running"
          sleep 10
      - name: Run third file
        run: |
          echo "build completed"
          sleep 10
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run one-line script
        run: |
          echo "Test running"
          sleep 10
      - name: Run third file
        run: |
          echo "Test completed"
          sleep 10
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run one-line script
        run: |
          echo "deploy running"
          sleep 10
      - name: Run third file
        run: |
          echo "deploy completed"          
          sleep 10
