# This is a basic workflow to help you get started with Actions

name: MyPipe1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: First Run temp1 
        run: echo "First run output"
      - name: Second run
        run: echo "Second run output"
